export const sagaActions = {
    FETCH_HOUSES_DATA_SAGA: "FETCH_HOUSES_DATA_SAGA",
    FETCH_CHARACTERS_DATA_SAGA: "FETCH_CHARACTERS_DATA_SAGA",
    PUT_SUCCESSFULL_API_CALLS_SAGA: "PUT_SUCCESSFULL_API_CALLS_SAGA"
  };
  